// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 18/10/2024, 1:05:34 p. m.
const configMerger = require("/home/freddfor/loginNuxtTailwind/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/freddfor/loginNuxtTailwind/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/freddfor/loginNuxtTailwind/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/freddfor/loginNuxtTailwind/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/freddfor/loginNuxtTailwind/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/freddfor/loginNuxtTailwind/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/freddfor/loginNuxtTailwind/plugins/**/*.{js,ts,mjs}","/home/freddfor/loginNuxtTailwind/composables/**/*.{js,ts,mjs}","/home/freddfor/loginNuxtTailwind/utils/**/*.{js,ts,mjs}","/home/freddfor/loginNuxtTailwind/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/freddfor/loginNuxtTailwind/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/freddfor/loginNuxtTailwind/app.config.{js,ts,mjs}"] } }));

module.exports = config
